### ISSUE TITLE
til validate silent on sucessfully validations

### ISSUE THREAD

**Issue by sameersbn** [triggermesh/til#182]
Currently `til validate` does not return any output on successful validations. The absence of command output makes the user second guess if the validation check actually took place. I believe we can improve the UX if the command by returning some informative text such as `bridge.brg.hcl validated sucessfully` or `bridge.brg.hcl validation completed, 0 errors found`.

**Comment by antoineco** [comment]
For context, the absence of output is simply a direct application of UNIX's "[rule of silence](http://www.linfo.org/rule_of_silence.html)". It's a pretty common thing across UNIX tools to not print anything **if there is nothing to pipe to another program**. `til validate` falls into that category, it doesn't generate data like `til generate` does.

If you feel strongly about changing that, I'd suggest remaining terse (e.g `"OK"`). We should also add a flag to opt out (e.g. `--quiet`) so that we can use `til validate && something` in a script without polluting stdout unnecessarily ("what does this `OK` mean in the middle of my script execution?"). We must also update both the command's help text as well as TriggerMesh's documentation.

**Comment by sameersbn** [comment]
With the `--quiet` flag we would still expect validation errors to be displayed right?

**Comment by antoineco** [comment]
Yes, everything that goes to stderr should be printed unconditionally.
