### ISSUE TITLE
block fields missing from API

### ISSUE THREAD

**Issue by tiewei** [triggermesh/til#189]
There are quite some fields supported in the API spec but missing in the `til`, this could be a deal-breaker to fully adopt `til` as the YAML generating tool.

While trying to poke around the code I found it seems intentionally avoid importing the type from `triggermesh`, is there a reason behind it? I think I could write something quick to generate the code for the `translation` interface if could use the type information.

**Comment by antoineco** [comment]
@tiewei these are all great suggestions and ideas 👍 

You are right, we do have some lag between `triggermesh` and `til` still, because `til` started as a research project to explore how we could more easily express messaging systems as a whole, and we didn't yet approach things like code generation and plug-ins.

Another reason why we haven't synchronized our components between `triggermesh` and `til` (automatically) is because the Go and HCL type systems are quite different, and in some cases we wanted the HCL version to be slightly different (e.g. credentials, or references to other objects).

If you have some ideas to reliably generate `til` integrations based on their Kubernetes object, feel free to share!

Meanwhile, could you please give some examples of issues you're currently having? What types did you find not to be in-sync?
I will address these quickly.

**Comment by tiewei** [comment]
yea, I was trying to make use of the `httppollersource` and found the header and auth are pretty common use cases that are missing. I'll have a PR for it.

I'll give it a try to see if I could generate them, though as you said in some cases the HCL version and object to be slightly different, it could be tricky to control.
